#This is a basic work flow that integrates the repository with SAST through CxFlow
name: CxFlow Local Runner
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  PROJECT_NAME: "Hello_World-DEV"
  SAST_PRESET: "OWASP TOP 10 - 2021"
  SAST_TEAM: "/CxServer/TeamA"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: self-hosted
    runs-on: self-hosted    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
        #CxFlow Action
      - name: CxFlow SAST Action
        run: >                        
            java -jar "C:\cxflow\cx-flow-1.7.0.jar" 
            --scan 
            --app="${{env.PROJECT_NAME }}"
            --cx-project="${{env.PROJECT_NAME }}" 
            --f="${{ github.workspace }}"  
            --spring.profiles.active="sast"                                   
            --cx-team="${{env.SAST_TEAM }}" 
            --checkmarx.scan-preset="${{env.SAST_TEAM }}" 
            --checkmarx.base-url="${{ secrets.CXSAST_URL }}" 
            --checkmarx.username="${{ secrets.CXSAST_USER_NAME }}" 
            --checkmarx.password="${{ secrets.CXSAST_USER_PASSWORD }}" 
            --cx-flow.zip-include="**/*.java"
            --logging.level.com.checkmarx.*=debug
