#This is a basic work flow that integrates the repository with SAST through CxFlow
name: CxFlow-SAST-SCA
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch 
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2       
      - name: Checkmarx CxFlow Action
        # You may pin to the exact commit or the version.
        # uses: checkmarx-ts/checkmarx-cxflow-github-action@9c07e2adcb17d0fdf60f3184ff53720513ea3c09
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.9
        with:
          # Vulnerability Scanners (sast, sca, cxgo)
          scanners: sast, sca
          # Provide Checkmarx URL
          checkmarx_url: ${{ secrets.CXSAST_URL }}
          # Select a Checkmarx Team
          team: /CxServer
          # Provide Checkmarx Username
          checkmarx_username: ${{ secrets.CXSAST_USER_NAME }}
          # Provide Checkmarx Password
          checkmarx_password: ${{ secrets.CXSAST_USER_PASSWORD }} 
          # Provide Checkmarx Client Secret
          checkmarx_client_secret: ${{secrets.CXSAST_CLIENT_SECRET}}
          # Select a Checkmarx Project
          project: ${{ github.repository }}
          # Select an Application Name used by downstream bug tracker systems
          app: ${{ github.repository }}
          # Select a Checkmarx Preset
          preset: High and Medium # optional, default is High and Medium
          # Break build based on Checkmarx findings?
          break_build: false # optional
          # Bug tracker for the scan results.
          bug_tracker: GITHUBPULL # optional, default is Sarif
          # Incremental Scans?
          incremental: false # optional, default is true
          # Provide SCA API URL
          sca_api_url: https://api-sca.checkmarx.net # optional, default is https://api.scacheckmarx.com
          # Provide SCA APP URL
          sca_app_url: https://sca.checkmarx.net # optional, default is https://sca.scacheckmarx.com
          # Provide SCA Access Control URL
          sca_access_control_url: https://platform.checkmarx.net # optional, default is https://platform.checkmarx.net
          # Provide SCA Tenant
          sca_tenant: ${{ secrets.CX_SCA_TENANT }}
          # Provide SCA Username
          sca_username: ${{ secrets.CX_SCA_USERNAME }} # optional, default is 
          # Provide SCA Password
          sca_password: ${{ secrets.CX_SCA_PASSWORD }} # optional, default is 
          # Additional CLI parameters
          params: --forceScan=true --checkmarx.cx-branch=true --namespace=${{ github.repository_owner }} --checkmarx.settings-override=true --repo-name=${{ github.event.repository.name }} --branch=${{ github.head_ref }} --merge-id=${{ github.event.number }} --logging.level.com.checkmarx.flow.service=debug --logging.level.com.checkmarx.flow.utils=debug --logging.level.com.checkmarx.sdk.service=debug --cx-flow.zip-exclude="\.git\/.*,\.github\/.*,apps\/tests\/.*,apps\/docs/.*,apps\/web\/.*,.*\/*.json,.*\/.md,.*\/.png"

                  
          # Subdirectory containing extra X509 certificate files (.crt) to be imported into the CxFlow JRE. Example: \"certificates\"
#          extra_certificates: # optional, default is 
#          
#          # Provide CxGo Client Secret
#          cxgo_client_secret: # optional, default is 
#          # Provide CxGo API URL
#          cxgo_base_url: # optional, default is https://api.checkmarx.net
#          # Provide CxGo Portal URL
#          cxgo_portal_url: # optional, default is https://cloud.checkmarx.net
#          # Java options will be passed to java
#          java_opts: # optional, default is -XX:MaxRAMPercentage=75.0
#          # Jira URL
#          jira_url: # optional, default is 
#          # Jira Username
#          jira_username: # optional, default is 
#          # Jira Token
#          jira_token: # optional, default is 
#          # Jira Project
#          jira_project: # optional, default is 
#          # Jira Issue Type
#          jira_issue_type: # optional, default is 
#          # Jira Open Transition
#          jira_open_transition: # optional, default is 
#          # Jira Close Transition
#          jira_close_transition: # optional, default is 
#          # Jira Open Status
#          jira_open_status: # optional, default is 
#          # Jira Closed Status
#          jira_closed_status: # optional, default is 
