#This is a basic work flow that integrates the repository with SAST through CxFlow

name: CxFlow-SAST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        #CxFlow Action
      - name: CxFlow Action
        # You may pin to the exact commit or the version.
        # uses: checkmarx-ts/checkmarx-cxflow-github-action@fe2a395cbbee31268470d92b6c53ebc483005f0f
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.3        
        with:          
          team: /CxServer/TesterTeam/t01
          project: HelloWorld-GitHub-action
          # Select an Application Name used by downstream bug tracker systems
          app: HelloWorld
          # GitHub API Token
          #github_token: ${{ secrets.GH_TOKEN }}
          # Vulnerability Scanners (sast, sca, ast, cxgo)
          #------ SAST ------
          scanners: sast
          # Provide Checkmarx URL
          checkmarx_url: ${{ secrets.SAST_URL }}
          # Provide team
          #team: /CxServer/SP/
          # Provide Checkmarx Username
          #checkmarx_username: ${{secrets.CHECKMARX_USERNAME}}
          # Provide Checkmarx Password
          #checkmarx_password: ${{secrets.CHECKMARX_PASSWORD}}
          # Provide Checkmarx Client Secret
          #checkmarx_client_secret: ${{secrets.CHECKMARX_CLIENT_SECRET}}
          # Select a Checkmarx Project
          #project: HelloWorld-GitHub-action          
          bug_tracker: JIRA          
          params: --config=cx.config --repo-name=${{ github.repository }} --namespace=TaynaCT --branch=master --jira.url=${{secrets.JIRA_URL}} --jira.username=${{secrets.JIRA_USER}} --jira.token=${{secrets.JIRA_TOKEN}}
          #Logs parameters
          #--logging.level.com.checkmarx.flow.custom=debug --logging.level.com.checkmarx.flow.service=debug --logging.level.com.checkmarx.flow.utils=debug --logging.level.com.checkmarx.sdk.service=debug
          
          
