#This is a basic work flow that integrates the repository with SAST through CxFlow
name: CxFlow Local Runner
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  PROJECT_NAME: "Hello_World-DEV"
  SAST_PRESET: "OWASP TOP 10 - 2021"
  SAST_TEAM: "/CxServer/TeamA"
  SAST_FILES_INCLUDE: '.*\.apex,.*\.apexp,.*\.app,.*\.asax,.*\.ascx,.*\.sp,.*\.aspx,.*\.bas,.*\.c,.*\.c++,.*\.cbl,.*\.cc,.*\.cgi,.*\.cls,.*\.cmp,.*\.cob,.*\.component,.*\.conf,.*\.config,.*\.cpp,.*\.cpy,.*\.cs,.*\.cshtml,.*\.ctl,.*\.ctp,.*\.cxx,.*\.dll,.*\.dsr,.*\.ec,.*\.eco,.*\.erb,.*\.evt,.*\.frm,.*\.go,.*\.gradle,.*\.groovy,.*\.gsh,.*\.gsp,.*\.gtl,.*\.gvy,.*\.gy,.*\.h,.*\.h++,.*\.handlebars,.*\.hbs,.*\.hh,.*\.hpp,.*\.htm,.*\.html,.*\.hxx,.*\.inc,.*\.jade,.*\.jar,.*\.java,.*\.js,.*\.jsf,.*\.json,.*\.jsp,.*\.jspf,.*\.jsx,.*\.kt,.*\.kts,.*\.lock,.*\.m,.*\.master,.*\.-meta.*\.xml,.*\.mf,.*\.mustache,.*\.object,.*\.page,.*\.pck,.*\.pco,.*\.php,.*\.php3,.*\.php4,.*\.php5,.*\.phtm,.*\.phtml,.*\.pkb,.*\.pkh,.*\.pks,.*\.pl,.*\.plist,.*\.pls,.*\.plx,.*\.pm,.*\.properties,.*\.psgi,.*\.pug,.*\.py,.*\.rb,.*\.report,.*\.rhtml,.*\.rjs,.*\.rxml,.*\.scala,.*\.sqb,.*\.sql,.*\.swift,.*\.tag,.*\.tgr,.*\.tld,.*\.tpl,.*\.trigger,.*\.ts,.*\.tsx,.*\.twig,.*\.vb,.*\.vbp,.*\.vbs,.*\.vm,.*\.vue,.*\.wod,.*\.workflow,.*\.xaml,.*\.xhtml,.*\.xib,.*\.xml,.*\.xsaccess,.*\.xsapp,.*\.xsjs,.*\.xsjslib'
  SAST_FILES_EXCLUDE: '\.settings/.*,\.m2/.*,\.nuget/.*,\.mvn/.*,\\maven/.*,\.nuget/.*,\build/.*,\documents/.*,\docs/.*,\swagger/.*,\lib/.*,\test/.*,\_cvs/.*,\.svn/.*, \.hg/.*, \.git/.*,\.bzr/.*,\.gitgnore/.*, \.gradle/.*, \.checkstyle/.*, \.classpath/.*,\bin/.*,\backup/.*, \.idea/.*,.*\.DS_Store, .*\.ipr, .*\.iws,.*\.bak,.*\.tmp,.*\.aac,.*\.aif, .*\.iff, .*\.m3u, .*\.mid, .*\.mp3,.*\.mpa, .*\.ra, .*\.wav, .*\.wma, .*\.3g2, .*\.3gp, .*\.asf, .*\.asx,.*\.avi, .*\.flv, .*\.mov, .*\.mp4, .*\.mpg, .*\.rm, .*\.swf, .*\.vob,.*\.wmv, .*\.bmp, .*\.gif, .*\.jpg, .*\.png, .*\.psd, .*\.tif, .*\.swf,  .*\.jar, .*\.zip, .*\.rar, .*\.exe, .*\.dll, .*\.pdb, .*\.7z, .*\.gz,.*\.tar.gz, .*\.tar, .*\.gz, .*\.ahtm, .*\.ahtml, .*\.fhtml, .*\.hdm,  .*\.hdml, .*\.hsql, .*\.ht, .*\.hta, .*\.htc, .*\.htd, .*\.war, .*\.ear,.*\.htmls, .*\.ihtml, .*\.mht, .*\.mhtm, .*\.mhtml, .*\.ssi, .*\.stm,  .*\.bin,.*\.lock,.*\.svg,.*\.obj,  .*\.stml, .*\.ttml, .*\.txn, .*\.xhtm, .*\.xhtml, .*\.class, .*\.iml, .*\.txt, .*\.log, .*\.md, .*\.gitignore, .*\.spec'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: self-hosted
    runs-on: self-hosted    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
        #CxFlow Action
      - name: CxFlow SAST Action
        run: >                        
            java -jar "C:\cxflow\cx-flow-1.7.0.jar" 
            --scan 
            --app="${{env.PROJECT_NAME }}"
            --cx-project="${{env.PROJECT_NAME }}" 
            --f="${{ github.workspace }}"  
            --spring.profiles.active="sast"                                   
            --cx-team="${{env.SAST_TEAM }}" 
            --checkmarx.scan-preset="${{env.SAST_TEAM }}" 
            --checkmarx.base-url="${{ secrets.CXSAST_URL }}" 
            --checkmarx.username="${{ secrets.CXSAST_USER_NAME }}" 
            --checkmarx.password="${{ secrets.CXSAST_USER_PASSWORD }}" 
            --cx-flow.zip-exclude="${{ env.SAST_FILES_EXCLUDE }}"
            --logging.level.com.checkmarx.*=debug
