# Checkmarx Documentation can be found at:
#  https://docs.checkmarx.com/en/34965-68702-checkmarx-one-github-actions.html
# The additional_params field, you can specify any CLI arguments that you would like to apply to scans of this project.

name: Checkmarx One Scan
on:
  pull_request:
    types:
      - opened
      - closed
    branches:
      - main
jobs:  
  build:
    env:
      #Checks if either the trgger even is a merge from a PR or not.
      #If a pull request was closed as a result of being merged, it will be the fully qualified ref of the branch it was merged into, for example /refs/heads/main. Refer to https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
      #Else the env.CURRENT_BRANCH receives the github.head_ref
      CURRENT_BRANCH: ${{ (github.event.pull_request.merged == true) && github.ref || github.head_ref }}
    runs-on: ubuntu-latest
    steps:             
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: ${{ github.repository }}
          cx_tenant: ${{ secrets.CXONE_TENANT }}
          base_uri: https://eu.ast.checkmarx.net
          cx_client_id: ${{ secrets.CXONE_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CXONE_CLENT_SECRET }}
          branch: ${{ env.CURRENT_BRANCH }}          
          additional_params:  --scan-types sast           
                              --sast-preset-name "ASA Premium"
                              --tags "pr:${{ github.ref }}"
                              --file-filter '!*README.md,!*app-hello-world*.js'
                              --sast-incremental true
                              #Configuring thresholds enables users to specify a threshold of vulnerability severities that, when found in a scan, will cause Checkmarx One to return a fail code for the scan.
                              #Refer to https://docs.checkmarx.com/en/34965-68643-scan.html#UUID-a0bb20d5-5182-3fb4-3da0-0e263344ffe7_id_scancreate-Threshold
                              --threshold "sast-high=10; sast-medium=20; sca-high=10; containers-high=5"
